# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.x'

    - name: Add SSH Go Module Private Key
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "Create SSH agent"
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "Add key"
          ssh-add - <<< "${{ secrets.GO_MODULE_PRIVATE_KEY }}"
          echo "Update env"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV 

    - name: Setup access for private go modules
      run: |
        git config --global url."ssh://git@github.com/".insteadOf https://github.com/        

    - name: Test engine
      working-directory: ./engine
      run: |
        go get 
        go test -v .
      
    - name: Test timeutils
      working-directory: ./timeutils
      run: go test -v .
      
